# Site specific settings
title: "bootingman's site"
name: "booting the man"
keywords: "Key, words, about, this, website"
baseurl: "/"
url: "https://bootingman.com"
description: "Website description"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "zh"
ssl: true # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: 
twitter: 
facebook: 
github: bootingman
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
